### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by SemenMartynov** [Yehuk/json_validator#2]
Please create user documentation and project description (README.md)

**Comment by Yehuk** [comment]
Done

**Comment by SemenMartynov** [comment]
Highlight the code please. It makes your documentation more readable.

**Comment by Yehuk** [comment]
Accidently closed

**Comment by Yehuk** [comment]
Fixed

**Comment by SemenMartynov** [comment]
I'm watching at the commit f8f3c3b:
`Showing with 0 additions and 0 deletions. `

**Comment by Yehuk** [comment]
It's strange, because there is 8 changes. Can you see the changes on the main page of this repository?
![image](https://user-images.githubusercontent.com/7442550/34937547-52ad112e-f9f6-11e7-91a2-38b4de5da4ad.png)

**Comment by SemenMartynov** [comment]
Really strange!)
![image](https://user-images.githubusercontent.com/1230054/34939338-78ca5348-f9fc-11e7-89ed-d765b44ed688.png)
