### ISSUE TITLE
JavaDoc

### ISSUE THREAD

**Issue by SemenMartynov** [Yehuk/json_validator#3]
Create JavaDoc for your code

**Comment by Yehuk** [comment]
Done

**Comment by SemenMartynov** [comment]
Nope. I can generate html files any time when I wish...
But you need to write JavaDoc for your code -- http://www.oracle.com/technetwork/articles/java/index-137868.html

**Comment by Yehuk** [comment]
What do mean? Should I write all these htmls?

**Comment by SemenMartynov** [comment]
Just read what is JavaDoc and add it to your java code.

**Comment by Yehuk** [comment]
Fixed

**Comment by SemenMartynov** [comment]
This is a step to the right direction.
So, you've called params, but didn't explain them.

**Comment by SemenMartynov** [comment]
And what about executions?

**Comment by Yehuk** [comment]
What executions? I have regular comments everywhere. Are they not enough?

**Comment by SemenMartynov** [comment]
Comments is a good thing, but now we are talking about JavaDoc.

**Comment by SemenMartynov** [comment]
And you again forgot about exceptions...)
I see Java is not your main language, isn't it?
